version: '3.8'

services:
  db:
    image: mariadb:lts
    container_name: frame24-mariadb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: lawtrel
      MARIADB_DATABASE: frame24
      MARIADB_USER: frame24
      MARIADB_PASSWORD: frame24pass
    volumes:
      - ./dump-frame24-202510112307.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: